# Persistent storage claim for Prometheus data
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prometheus-pvc
  namespace: nyc-vision-zero-platform
spec:
  accessModes:
    - ReadWriteOnce  # Only one node can mount this volume at a time (sufficient for single replica)
  resources:
    requests:
      storage: 5Gi  # Size of the volume requested

---
# ConfigMap for Prometheus configuration file
apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: nyc-vision-zero-platform
  labels:
    app: prometheus
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s  # How frequently Prometheus scrapes targets
    scrape_configs:
      - job_name: prometheus
        static_configs:
          - targets: ['localhost:9090']  # Default target: itself

---
# Prometheus Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus
  namespace: nyc-vision-zero-platform
spec:
  replicas: 1  # Single Prometheus instance
  selector:
    matchLabels:
      app: prometheus
  template:
    metadata:
      labels:
        app: prometheus
    spec:
      containers:
        - name: prometheus
          image: prom/prometheus:latest
          ports:
            - containerPort: 9090  # Exposes the Prometheus web UI and API
          volumeMounts:
            - name: config
              mountPath: /etc/prometheus  # Prometheus reads its config from here
            - name: data
              mountPath: /prometheus  # Prometheus stores its TSDB data here
      volumes:
        - name: config
          configMap:
            name: prometheus-config  # Mount the ConfigMap as a volume
        - name: data
          persistentVolumeClaim:
            claimName: prometheus-pvc  # Use the PVC for persistent storage

---
# Service to expose Prometheus
apiVersion: v1
kind: Service
metadata:
  name: prometheus
  namespace: nyc-vision-zero-platform
spec:
  selector:
    app: prometheus
  ports:
    - port: 9090
      targetPort: 9090
      protocol: TCP
  externalIPs:
    - {{ .Values.prometheus.externalIP }}  # External IP specified in Helm values
