---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ray-head
  namespace: nyc-vision-zero-platform
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ray
      role: head
  template:
    metadata:
      labels:
        app: ray
        role: head
    spec:
      containers:
        - name: ray-head
          image: rayproject/ray:latest
          ports:
            - containerPort: 8265 # dashboard
            - containerPort: 6379 # redis
          command: ['/bin/sh', '-c']
          args:
            - |
              ray start --head --port=6379 --dashboard-host=0.0.0.0 --dashboard-port=8265
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ray-worker
  namespace: nyc-vision-zero-platform
spec:
  replicas: {{ .Values.ray.workerReplicas }}
  selector:
    matchLabels:
      app: ray
      role: worker
  template:
    metadata:
      labels:
        app: ray
        role: worker
    spec:
      containers:
        - name: ray-worker
          image: rayproject/ray:latest
          command: ['/bin/sh', '-c']
          args:
            - ray start --address=ray-head:6379
---
apiVersion: v1
kind: Service
metadata:
  name: ray-head
  namespace: nyc-vision-zero-platform
spec:
  selector:
    app: ray
    role: head
  ports:
    - port: 8265
      targetPort: 8265
      name: dashboard
    - port: 6379
      targetPort: 6379
      name: redis
  externalIPs:
    - {{ .Values.ray.externalIP }}
